name: rustfmt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        rustup toolchain install nightly --allow-downgrade -c rustfmt
    - name: Check
      run: cargo +nightly fmt -- --check
